server:
  port: 8088
spring:
  data:
    redis:
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/gateway
    username: dhananjai
    password: Ammu123*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update